@baseURL = http://localhost:8000/api

# Account

# @name Register
POST {{baseURL}}/account/register
Content-Type: application/json

{   "email":"test@example.com",
    "username":"tranquocliem",
    "fullname":"Trần Quốc Liêm",
    "website":"https://github.com/tranquocliem",
    "phone":"0782872822",
    "story":"Xin chào các bạn đã đến với trang cá nhân của mình",
    "password":"123456"
}

###

# @name Login
POST {{baseURL}}/account/login
Content-Type: application/json

{
    "username":"tranquocliem",
    "password":"123456"
}

###

# @name Logout
GET {{baseURL}}/account/logout

###

# @name GetUser
GET {{baseURL}}/account/getUser?username=tranquocliem

###

# @name UpdateUser
PATCH  {{baseURL}}/account/updateUser
Content-Type: application/json

{
    "avatar":"https://res.cloudinary.com/devatchannel/image/upload/v1602752402/avatar/avatar_cugq40.png", 
    "fullname":"Trần Quốc Liêm", 
    "phone":"0782872822", 
    "story":"Xin chào các bạn đã đến với trang cá nhân của mình", 
    "website":"https://github.com/tranquocliem", 
    "gender":"Nam"
}

###

# @name DeleteAvatar
GET  {{baseURL}}/account/destroyAvatar

###

# @name SearchUser
GET {{baseURL}}/account/searchUser?username=quocliem

###

# @name Authenticated
GET {{baseURL}}/account/authenticated

###

# @name Follow
POST {{baseURL}}/follow/following
Content-Type: application/json

{
    "followers":"60744b85dd939243f4120031"
}

###

# @name UnFollow
DELETE {{baseURL}}/follow/unfollow
Content-Type: application/json

{
    "followers":"60744b6bdd939243f4120030"
}

###

# @name GetMyFollowing
GET {{baseURL}}/follow/getMyFollowing

###

# @name GetMyFollowers
GET {{baseURL}}/follow/getMyFollowers

###

# @name GetFollowing
POST  {{baseURL}}/follow/getFollowing
Content-Type: application/json

{
    "id":"60744bdadd939243f4120032"
}

###

# @name GetFollowers
POST  {{baseURL}}/follow/getFollowers
Content-Type: application/json

{
    "id":"60744bdadd939243f4120032"
}

###

# @name GetPosts
POST {{baseURL}}/post/getPost
Content-Type: application/json

{
    "skip":6
}

###

# @name GetPostsById
GET   {{baseURL}}/post/postById?id=607a51f922b9401064cf6025

###

# @name GetPostsByWriter
GET {{baseURL}}/post/postByWriter?writer=60744a94ead6c73ee8dfd9a3

###

# @name DestroyImages
POST  {{baseURL}}/post/destroyImages
Content-Type: application/json

{
    "public_id":[
        "test/IMG_0013_dofdxa",
        "test/IMG_0048_e3hc3i",
        "test/IMG_0012_o6ew51",
        "test/IMG_0015_mw69uj",
        "test/avartar_tgarqi"
    ]
}

###

# @name UpdatePost
PATCH {{baseURL}}/post/updatePost?id=607972a4d91c493b6c47cace
Content-Type: application/json

{
    "content":"Test Update",
    "images" : [ 
        {
            "public_id" : "instagirl/snz7jwrn2wpjenlakbwc",
            "url" : "https://res.cloudinary.com/tranquocliem/image/upload/v1618571940/instagirl/snz7jwrn2wpjenlakbwc.png"
        }
    ]
}

###

# @name Suggestions
GET {{baseURL}}/account/suggestions

###

# @name DropHeart
POST  {{baseURL}}/heart/dropHeart
Content-Type: application/json

{
    "postId":"607a51f922b9401064cf6025"
}

###

# @name UnHeart
DELETE {{baseURL}}/heart/unHeart?postId=607a51f922b9401064cf6025

###

# @name GetHeart
GET    {{baseURL}}/heart/getHeart?id=607a51f922b9401064cf6025

###

# @name GetHeartPost
GET    {{baseURL}}/heart/getHeartPost?id=607a51f922b9401064cf6025

###

# @name GetCommentByPostId
GET    {{baseURL}}/comment/getComment?postId=607ea73a96e54c1b1c2c103c&limit=2

###

# @name UpdateComment
PATCH  {{baseURL}}/comment/updateComment?_id=607fd6d2b747a30200c3c57c
Content-Type: application/json

{
    "content":"Comment 14 Updated"
}

###

# @name UpdateReplyComment
PATCH  {{baseURL}}/replycomment/updateReplyComment?_id=608106127f8f2d3f7491e345
Content-Type: application/json

{
    "content":"Cung quan điểm luôn trời"
}

###

# @name DeleteComment
DELETE {{baseURL}}/comment/deleteComment?_id=6081511e17fca809502a3f7f

###

# @name DeleteReplyComment
DELETE {{baseURL}}/replycomment/deleteReplyComment?_id=60815070eb5f1a2e2c209aef

###

# @name DropHeartComment
POST {{baseURL}}/heartcomment/dropHeartComment
Content-Type: application/json

{
    "commentId":"607fd6d2b747a30200c3c57c"
}

###

# @name UnHeartComment
DELETE {{baseURL}}/heartcomment/unHeartComment?commentId=607fd6d2b747a30200c3c57c

###

# @name GetHeartComment
GET {{baseURL}}/heartcomment/getHeartComment?id=607fd6d2b747a30200c3c57c