@baseURL = http://localhost:8000/api

# Account

# @name Register
POST {{baseURL}}/account/register
Content-Type: application/json

{   "email":"test@example.com",
    "username":"tranquocliem",
    "fullname":"Trần Quốc Liêm",
    "website":"https://github.com/tranquocliem",
    "phone":"0782872822",
    "story":"Xin chào các bạn đã đến với trang cá nhân của mình",
    "password":"123456"
}

###

# @name Login
POST {{baseURL}}/account/login
Content-Type: application/json

{
    "username":"tranquocliem",
    "password":"123456"
}

###

# @name Logout
GET {{baseURL}}/account/logout

###

# @name GetUser
GET {{baseURL}}/account/getUser?username=tranquocliem

###

# @name UpdateUser
PATCH  {{baseURL}}/account/updateUser
Content-Type: application/json

{
    "avatar":"https://res.cloudinary.com/devatchannel/image/upload/v1602752402/avatar/avatar_cugq40.png", 
    "fullname":"Trần Quốc Liêm", 
    "phone":"0782872822", 
    "story":"Xin chào các bạn đã đến với trang cá nhân của mình", 
    "website":"https://github.com/tranquocliem", 
    "gender":"Nam"
}

###

# @name DeleteAvatar
GET  {{baseURL}}/account/destroyAvatar

###

# @name SearchUser
GET {{baseURL}}/account/searchUser?username=quocliem

###

# @name Authenticated
GET {{baseURL}}/account/authenticated

###

# @name Follow
POST {{baseURL}}/follow/following
Content-Type: application/json

{
    "followers":"60744b85dd939243f4120031"
}

###

# @name UnFollow
DELETE {{baseURL}}/follow/unfollow
Content-Type: application/json

{
    "followers":"60744b6bdd939243f4120030"
}

###

# @name GetMyFollowing
GET {{baseURL}}/follow/getMyFollowing

###

# @name GetMyFollowers
GET {{baseURL}}/follow/getMyFollowers

###

# @name GetFollowing
POST  {{baseURL}}/follow/getFollowing
Content-Type: application/json

{
    "id":"60744bdadd939243f4120032"
}

###

# @name GetFollowers
POST  {{baseURL}}/follow/getFollowers
Content-Type: application/json

{
    "id":"60744bdadd939243f4120032"
}

###

# @name GetPosts
GET   {{baseURL}}/post/getPost
