@baseURL = http://localhost:8000/api

// ------------------------------------------------------------ ACCOUNT ------------------------------------------------------------ //
# @name Register
POST {{baseURL}}/account/register
Content-Type: application/json

{   "email":"quocliem1999@gmail.com",
    "username":"quocliem1999",
    "fullname":"Trần Quốc Liêm",
    "password":"123456"
}

###

# @name ActivationAccount
POST {{baseURL}}/account/activation
Content-Type: application/json

{   
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InF1b2NsaWVtMTk5OUBnbWFpbC5jb20iLCJmdWxsbmFtZSI6IlRy4bqnbiBRdeG7kWMgTGnDqm0iLCJ1c2VybmFtZSI6InF1b2NsaWVtMTk5OSIsInBhc3N3b3JkSGFzaCI6IldOdUM2VnhXdHJyNUdKaElQNlZVM0JLeWZpb3ZlMythSFpQV2RFSUprYUVxOENxZit0TDVvNHB2SG1HTFpJTUtjQitpK2gvY1JnaDVTb1JxUWFrdUZCRm91WThqU3ZjeWFaSlllQzdjcUlSWVh2ZVhzODFQY1p5eFZQS2ZHZVlyRU5kVURQeUlwSzVEZ1NJVWZHejM4NkVla3FWRnFFRkV5Sk9yUmxxVHZHcz0iLCJpYXQiOjE2MTk3NzA1NzYsImV4cCI6MTYxOTg1Njk3Nn0.tsUbNNP3-ZLNyOook9IWWlo3ryiJZVkpnLsjZP8nWTM"
}

###

# @name Login
POST {{baseURL}}/account/login
Content-Type: application/json

{
    "username":"quocliem1999@gmail.com",
    "password":"123456"
}

###

# @name Logout
GET {{baseURL}}/account/logout

###

# @name ForgetPass
POST  {{baseURL}}/account/forgetPass
Content-Type: application/json

{
    "email":"quocliem1999@gmail.com"
}

###

# @name ResetPass
POST  {{baseURL}}/account/resetPass
Content-Type: application/json

{
    "resetLink":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDhiZjZiNzE3YzRlNzNiYjgwZWM0YTQiLCJpYXQiOjE2MTk3ODU0MjAsImV4cCI6MTYxOTc4NjAyMH0.80LydUWn29VykbmxMOILgJWSwhlDSlBZo1bA7RCxMa0",
    "newPassword":"123456"
}

###

# @name GetUser
GET {{baseURL}}/account/getUser?username=tranquocliem

###

# @name UpdateUser
PATCH  {{baseURL}}/account/updateUser
Content-Type: application/json

{
    "avatar":"https://res.cloudinary.com/devatchannel/image/upload/v1602752402/avatar/avatar_cugq40.png", 
    "fullname":"Trần Quốc Liêm", 
    "phone":"0782872822", 
    "story":"Xin chào các bạn đã đến với trang cá nhân của mình", 
    "website":"https://github.com/tranquocliem", 
    "gender":"Nam"
}

###

# @name DeleteAvatar
GET  {{baseURL}}/account/destroyAvatar

###

# @name SearchUser
GET {{baseURL}}/account/searchUser?username=quocliem

###

# @name Authenticated
GET {{baseURL}}/account/authenticated

###

# @name Suggestions
GET {{baseURL}}/account/suggestions

###

// ------------------------------------------------------------ ACCOUNT ------------------------------------------------------------ //



// ------------------------------------------------------------ FOLLOW ------------------------------------------------------------ //
# @name Follow
POST {{baseURL}}/follow/following
Content-Type: application/json

{
    "followers":"60744b85dd939243f4120031"
}

###

# @name UnFollow
DELETE {{baseURL}}/follow/unfollow
Content-Type: application/json

{
    "followers":"60744b6bdd939243f4120030"
}

###

# @name GetMyFollowing
GET {{baseURL}}/follow/getMyFollowing

###

# @name GetMyFollowers
GET {{baseURL}}/follow/getMyFollowers

###

# @name GetFollowing
POST  {{baseURL}}/follow/getFollowing
Content-Type: application/json

{
    "id":"60744bdadd939243f4120032"
}

###

# @name GetFollowers
POST  {{baseURL}}/follow/getFollowers
Content-Type: application/json

{
    "id":"60744bdadd939243f4120032"
}

###

// ------------------------------------------------------------ FOLLOW ------------------------------------------------------------ //



// ------------------------------------------------------------ POST ------------------------------------------------------------ //
# @name GetPosts
POST {{baseURL}}/post/getPost
Content-Type: application/json

{
    "skip":6
}

###

# @name GetPostsById
GET   {{baseURL}}/post/postById?id=607a51f922b9401064cf6025

###

# @name GetPostsByWriter
GET {{baseURL}}/post/postByWriter?writer=60744a94ead6c73ee8dfd9a3&skip=0

###

# @name GetPostsDiscover
GET {{baseURL}}/post/getPostDiscover?skip=0

###

# @name DestroyImages
POST  {{baseURL}}/post/destroyImages
Content-Type: application/json

{
    "public_id":[
        "test/IMG_0013_dofdxa",
        "test/IMG_0048_e3hc3i",
        "test/IMG_0012_o6ew51",
        "test/IMG_0015_mw69uj",
        "test/avartar_tgarqi"
    ]
}

###

# @name UpdatePost
PATCH {{baseURL}}/post/updatePost?id=607972a4d91c493b6c47cace
Content-Type: application/json

{
    "content":"Test Update",
    "images" : [ 
        {
            "public_id" : "instagirl/snz7jwrn2wpjenlakbwc",
            "url" : "https://res.cloudinary.com/tranquocliem/image/upload/v1618571940/instagirl/snz7jwrn2wpjenlakbwc.png"
        }
    ]
}

###

# @name DeletePost
DELETE {{baseURL}}/post/deletePost?_id=608543fd0ac0d32428ec2b45

###

// ------------------------------------------------------------ POST ------------------------------------------------------------ //



// ------------------------------------------------------------ HEART ------------------------------------------------------------ //
# @name DropHeart
POST  {{baseURL}}/heart/dropHeart
Content-Type: application/json

{
    "postId":"607a51f922b9401064cf6025"
}

###

# @name UnHeart
DELETE {{baseURL}}/heart/unHeart?postId=607a51f922b9401064cf6025

###

# @name GetHeart
GET    {{baseURL}}/heart/getHeart?id=607a51f922b9401064cf6025

###

# @name GetHeartPost
GET    {{baseURL}}/heart/getHeartPost?id=607a51f922b9401064cf6025

###

// ------------------------------------------------------------ HEART ------------------------------------------------------------ //



// ------------------------------------------------------------ COMMENT ------------------------------------------------------------ //
# @name GetCommentByPostId
GET    {{baseURL}}/comment/getComment?postId=607ea73a96e54c1b1c2c103c&limit=2

###

# @name UpdateComment
PATCH  {{baseURL}}/comment/updateComment?_id=607fd6d2b747a30200c3c57c
Content-Type: application/json

{
    "content":"Comment 14 Updated"
}

###

# @name DeleteComment
DELETE {{baseURL}}/comment/deleteComment?_id=6081511e17fca809502a3f7f

###

// ------------------------------------------------------------ COMMENT ------------------------------------------------------------ //



// ------------------------------------------------------------ REPLYCOMMENT ------------------------------------------------------------ //
# @name UpdateReplyComment
PATCH  {{baseURL}}/replycomment/updateReplyComment?_id=608106127f8f2d3f7491e345
Content-Type: application/json

{
    "content":"Cung quan điểm luôn trời"
}

###

# @name DeleteReplyComment
DELETE {{baseURL}}/replycomment/deleteReplyComment?_id=60815070eb5f1a2e2c209aef

###

// ------------------------------------------------------------ REPLYCOMMENT ------------------------------------------------------------ //



// ------------------------------------------------------------ HEARTCOMMENT ------------------------------------------------------------ //
# @name DropHeartComment
POST {{baseURL}}/heartcomment/dropHeartComment
Content-Type: application/json

{
    "commentId":"607fd6d2b747a30200c3c57c"
}

###

# @name UnHeartComment
DELETE {{baseURL}}/heartcomment/unHeartComment?commentId=607fd6d2b747a30200c3c57c

###

# @name GetHeartComment
GET {{baseURL}}/heartcomment/getHeartComment?id=607fd6d2b747a30200c3c57c

###

// ------------------------------------------------------------ HEARTCOMMENT ------------------------------------------------------------ //



// ------------------------------------------------------------ SAVEPOST ------------------------------------------------------------ //
# @name SavePost
POST {{baseURL}}/post/savePost
Content-Type: application/json

{
    "postId":"6083e9c14a644e33a890fb5b"
}

###

# @name GetSavePostByUser
GET {{baseURL}}/savepost/getSavePostByUser

###

# @name GetSavePostByPost
GET {{baseURL}}/savepost/getSavePostByPost?postId=6083e9c14a644e33a890fb5b

###

# @name DeleteSavePost
DELETE {{baseURL}}/post/deleteSavePost?postId=6083e9c14a644e33a890fb5b

// ------------------------------------------------------------ SAVEPOST ------------------------------------------------------------ //

// ------------------------------------------------------------ NOTIFY ------------------------------------------------------------ //

###

# @name GetNotify
GET  {{baseURL}}/notify/getNotify

###

# @name DeleteNotify
DELETE {{baseURL}}/notify/deleteNotify?id=608a3144cd8ce200e80dac75

###

# @name DeleteAllNotify
DELETE   {{baseURL}}/notify/deleteAllNotify

// ------------------------------------------------------------ NOTIFY ------------------------------------------------------------ //

###

# @name SavePost
POST {{baseURL}}/post/uploadImage
Content-Type: application/json

{
    "images":[{"type": "image/png"}]
}

###